### ISSUE TITLE
Separate API from CLI

### ISSUE THREAD

**Issue by ZebraFlesh** [finn-no/maven-deploy#16]
The API and the CLI concerns are combined and should be separated. For example, I want to be able to call this from another package and wrap it in an ES6 promise.  However, once I call into deploy(), if there's any sort of issue the process simply exits -- there's no chance to reject a promise.  A better approach would be to provide all of the API data in a callback so it could be wrapped in a promise; it would then be up to the caller how to handle it.

Making a separate CLI is straight forward: add a "bin" config to package.json, point it to a file that has a node shebang, and require the main part of your code.

**Comment by gregersrygg** [comment]
:+1: Would you like to make a pull-request?

**Comment by gregersrygg** [comment]
474296d fixes that the process exits, so the error is passed to the callback. Should fix your issue. Please verify :)

I don't understand what the CLI is supposed to do. `mvn` itself *is* a CLI, this is just a js-lib to use instead.

**Comment by gregersrygg** [comment]
I've been thinking a bit more about the CLI idea, and it could be quite nice to have a simple CLI for this. By using the maven-config.json by default (possibly another filename as command line arg), you probably won't need any options at all.

Do you want to give it a shot?
