### ISSUE TITLE
Dclisifier=undefined

### ISSUE THREAD

**Issue by antoniopuero** [finn-no/maven-deploy#20]
if I don't provide any clisifer inside the config it fails, cause maven executes with -Dclisifier=undefined argument. Some additional check will help  `classifier   : conf.classifier`

**Comment by antoniopuero** [comment]
Created pr to that issue #21

**Comment by gregersrygg** [comment]
Whops. Thanks for the PR! Published 1.2.1

**Comment by antoniopuero** [comment]
nice! no problemo

**Comment by gregersrygg** [comment]
Added you as a contributor, so now you can push directly. Let me know if you want feedback/code-review on anything :)

**Comment by antoniopuero** [comment]
Cool! Thanks :) I apreciate it
