### ISSUE TITLE
Make automatic packaging optional

### ISSUE THREAD

**Issue by micha149** [finn-no/maven-deploy#22]
In some cases I wan't to deploy a already packaged file. As I understand your code, files from dist folder will always be packaged. Can we make this optional? This could be done by a config option or a detection if buildDir ist Path to a packaged file…

**Comment by antoniopuero** [comment]
IMO your task has a bit different purpose so `maven.redeploy` or `maven.deployPrevious` function should be implemented. Otherwise `maven.deploy` will always see the same packaged file in dist folder and push it to the repo so only manual cleanup before deploy will fix that. Anyway it's a good point.

**Comment by micha149** [comment]
My purpose is to include this module into a gulp build pipeline and this should look like:

1. Do anything to get files
2. do anything to pack them as you want
3. deploy the packaged file to maven repository

I don't know if a `maven.redeploy` or `maven.deployPrevious` would match my needs. It sounds like it would not be able to deploy an all new version.

**Comment by gregersrygg** [comment]
I agree the current implementation doesn't work very well with Gulp. The config option sounds like a nice solution. Should be easy to just skip the `this.package(isSnapshot)` if the input filename option is supplied. Do you want to make a pull request for it? :innocent:

**Comment by micha149** [comment]
I thought a little bit about a suitable solution. I think two diffrent properties can be a bit confusing for users. For example: When you pass `buildDir` and `inputFile` both, what can you expect from the module?

I would suggest to stay on the single `buildDir` property and use `fs.Stat.isFile()` to check if the path points to a single file. In this case automatic packaging would be disabled and the file will be ingested as it is. Additionally we can offer the property `forcePackaging` for users who want to compress a single file…

**Comment by micha149** [comment]
The more I get into the `maven-deploy` module, the less I think that this feature is a good idea.

I am not sure hot to handle properly `archivePath()`. In case of an already packaged file, its file name is the archive path. But what if the user wants to change the final name?! Copying the file would leave a mess on the filesystem…

**Comment by gregersrygg** [comment]
We have a breaking change in the pipeline, so we could consider breaking backwards compatibility to solve this in a clean manner. I haven't been very happy that this package makes the archive *and* executes `mvn`. It's against the single responsibility principle. Haven't looked at how much work it would be, but hopefully we can extract the part that makes the archive and publish it as a separate module people can use instead. Then we'd only need `inputFile` (or `file` which `mvn` use).

**Comment by micha149** [comment]
OK, your decision. I think its not required to created an extra module for creating the package. For this you can simply use `node-archiver` or something similar.

So, this package stay only as a wrapper around the mvn command?!

**Comment by ankon** [comment]
I'd really love to see this plugin _only_ doing the maven interaction (`deploy` & `install` goals), and leave the packaging to the outside build processes. In our case we're using [gulp-war](https://www.npmjs.com/package/gulp-war) to produce a .war file.

**Comment by micha149** [comment]
Already done in PR #29, but needs to be merged. I also made necessary changes in gulp-maven-delpoy and will push them when this PR was merged.
