### ISSUE TITLE
Enable setting the -s option (settings file)

### ISSUE THREAD

**Issue by ondrejchmelar** [finn-no/maven-deploy#24]
I miss a way to specify a settings file for the mvn command. 
The config should accept a "settingsFile" key and use it with the -s option (mvn -s my-settings.xml).

I can create a pull request, unless there is a reason it has not been done?

**Comment by rbellamy** [comment]
Why was this issue closed? It's a great feature request...

**Comment by ondrejchmelar** [comment]
Sorry, don't remember why this got closed, probably didn't need it eventually. 
Care to reopen?
