### ISSUE TITLE
Folders should be included in packaged archive (war/jar)

### ISSUE THREAD

**Issue by erikgb** [finn-no/maven-deploy#26]
I am trying to use maven-deploy to deploy a WebJar artifact to our Maven repository. This allows us to build frontend code (javascript, css etc.) with frontend build tools like Node.js/npm, but also support easy use of produced frontend code in Java/Maven based projects; by having dependencies to WebJars deployed to Maven/Nexus.

Loading WebJars in Java applications is heavily dependant on classpath scanning - in particular **classpath scanning of directories** (i.e. to determine the version of the WebJar).
The problem is that a WebJar installed/deployed with maven-deploy is currently unusable as a WebJar because **folders are not included when creating the archive** (package). For additional details see similar issue in grunt-contrib-compress: gruntjs/grunt-contrib-compress#90

I have looked into the source code (of maven-deploy), and think I this could be easily fixed - hopefully without any breaking changes. I will prepare a pull request and hopefully someone can merge the PR back and release a bugfix version.

**Comment by gregersrygg** [comment]
We are using maven-deploy to make WebJars in one of our projects successfully. Can you give some more info about what problem you're seeing?

```js
#!/usr/bin/env node

require('shelljs/make');
var path = require('path');
var fs = require('fs');
var semver = require('semver');
var maven = require('maven-deploy');
maven.config(require('./maven-config.json'));

var WEBJAR_FOLDER = path.join('dist', 'META-INF', 'resources', 'webjars', 'analytics-js');

function getPkgVersion () {
    return JSON.parse(fs.readFileSync('./package.json')).version;
}

target.copyToMetaInfResources = function (isSnapshot) {
    var version = getPkgVersion();
    if (isSnapshot) {
        version = semver.inc(version, 'patch') + '-SNAPSHOT';
    }
    var webjarVersionFolder = path.join(WEBJAR_FOLDER, version);
    mkdir('-p', webjarVersionFolder);
    cp('-rf', 'dist/analytics*', webjarVersionFolder);
};

target.install = function () {
    target.copyToMetaInfResources(true);
    maven.install();
};

target.snapshot = function () {
    target.copyToMetaInfResources(true);
    maven.deploy('finntech-internal-snapshot', true);
};

target.deploy = function () {
    target.copyToMetaInfResources();
    maven.deploy('finntech-internal-release', false);
};

target.all = target.build;
```

**Comment by erikgb** [comment]
The problem is fairly well explained in the referenced issue (gruntjs/grunt-contrib-compress#90), but I will try to summarize with a sample:

If you check the produced jar file with a command like tool like unzip:

    unzip -l sn-bonita-2.0.0-SNAPSHOT.jar

You will see that the folders are not included in the jar-file (the folders are just referenced):

    META-INF/resources/webjars/sn-bonita/2.0.0-SNAPSHOT/oisadm/css/sn-app.css

But with #27 in place, the same command gives the following output:

    META-INF/
    META-INF/resources/
    META-INF/resources/webjars/
    META-INF/resources/webjars/sn-bonita/
    META-INF/resources/webjars/sn-bonita/2.0.0-SNAPSHOT/
    META-INF/resources/webjars/sn-bonita/2.0.0-SNAPSHOT/oisadm/
    META-INF/resources/webjars/sn-bonita/2.0.0-SNAPSHOT/oisadm/css/
    META-INF/resources/webjars/sn-bonita/2.0.0-SNAPSHOT/oisadm/css/sn-app.css

The latter (folders included) is required when loading the css from the WebJar in our Java application (*current* version):

    sn-bonita/current/oisadm/css/sn-app.css

Since you are using maven-deploy to make usable WebJars, this might be an issue in the way we are trying to use our WebJar. However, I cannot see that including folders (and not just referencing them) in the packaged artifact can harm anyone. The only potentially breaking change by merging #27 could be that empty folders will now be included in the archive.

**Comment by gregersrygg** [comment]
Ah, now I understand. Thanks for the nice explanation, and good work :+1: 
Would you mind creating a test for this? I guess the test *«should zip file with unix-style path»* is pretty close to what you want.
