### ISSUE TITLE
Unable to use version 1.3.1 (after upgrade of dependency to isbinaryfile?)

### ISSUE THREAD

**Issue by erikgb** [finn-no/maven-deploy#28]
I am uable to use version 1.3.1. I get the following error:

```
/opt/jenkins/jobs/Styleguide 2.0 (npm)/workspace/node_modules/gulp-maven-deploy/node_modules/maven-deploy/node_modules/isbinaryfile/index.js:21
                return cb(null, isBinaryCheck(bytes, size));
                       ^

TypeError: cb is not a function
    at /opt/jenkins/jobs/Styleguide 2.0 (npm)/workspace/node_modules/gulp-maven-deploy/node_modules/maven-deploy/node_modules/isbinaryfile/index.js:21:24
    at /opt/jenkins/jobs/Styleguide 2.0 (npm)/workspace/node_modules/gulp-sourcemaps/node_modules/graceful-fs/graceful-fs.js:42:10
    at FSReqWrap.oncomplete (fs.js:82:15)
```

To me it seems like the API of isbinaryfile has changed in version 3.0.x (major version dependency upgrade), and the usage must be updated accordingly.

Also I do not understand why the tests do to detect this rather obvious bug…

**Comment by gregersrygg** [comment]
I looked through all projects with major version changes, but isbinaryfile didn't have a changelog or a useful commit-log (to find what the breaking change was). So I trusted the tests :(
Should be easy to fix this, but would like the tests to catch this... I'm not sure why the tests aren't failing either. Will see if it's an easy fix.

**Comment by erikgb** [comment]
Great! Keep me posted! The fix is very simple, but to fix the tests - I do not know....

**Comment by gregersrygg** [comment]
Seems like this is the commit with the breaking change: https://github.com/gjtorikian/isBinaryFile/commit/aac87cf7ba4832a8cdad1231f72428c5f651a0a1

**Comment by gregersrygg** [comment]
According to the coverage report, the call to isbinaryfile is covered: https://coveralls.io/builds/4924628/source?filename=index.js#L162 :confused:

**Comment by micha149** [comment]
Same problem here. isBinaryFile changed its interface from 2.0.4 to 3.0.0. You must use `isBinaryFile.sync(filePath)` now.

I think you should avoid dependencies to a newer major version in the future :wink:

**Comment by erikgb** [comment]
Well, I think it's ok to upgrade to newer major versions if the test coverage is good enough. :smile: 
@micha149 : Do you understand why the tests are not failing on this breaking change?

**Comment by eXaminator** [comment]
My guess is that `proxyquire` keeps the tests running somehow.

**Comment by gregersrygg** [comment]
@micha149 Yes, as I said it's easy to fix. Everyone npm package should try to keep up with major versions, if not we will all be in dependency hell. I just wish every package had a clear changelog with what the breaking changes was.

The reason it's not caught by the test is because the function changed from sync (and async) to async. So it will always return `undefined` which coerces to false in our if-test. Then the test passes, and a bit later the exception is thrown, but probably too late for Mocha to detect it. I can't think of a clean way to catch these kind of changes, so will just fix the bug.

**Comment by gregersrygg** [comment]
Released 1.3.2 now. Sorry for breaking stuff :disappointed:

**Comment by erikgb** [comment]
Thanks! I confirm that version 1.3.2 is working - with directories in archive. :smile:

**Comment by gregersrygg** [comment]
@erikgb Great!

I managed to create a test that would have failed (643edd3). We didn't have a test for binary files, so we never tested anything that expected isbinaryfile to return a truthy value. Now we do!
