### ISSUE TITLE
Expose version or snapshot option for installs

### ISSUE THREAD

**Issue by sebastianhenneberg** [finn-no/maven-deploy#35]
Hello there, thank you very much for maintaining this useful package!

Would it be possible to expose the version or snapshot option? I want to install stable releases for testing purposes. Unfortunately, `install()` always set `snapshot=true` and does not allow the specify this from the outside.

I actually need this functionality in `gulp-maven-deploy`. ;)

**Comment by micha149** [comment]
Version should be already configurable within the options object. I am not shure if it makes sense to use install without `snapshot=true`. It will not download  a stable version from a repository, it just copies the given files to your local maven repo… Would this not make Problems with updating this packages in your local repo?

**Comment by sebastianhenneberg** [comment]
Alright, thank you!

**Comment by karolmie1** [comment]
It would make sense if you were doing small project by yourself, and don't want to run your own nexus, and just rely on local repository. The option could be hidden, but it should be possible.
